"""empty message

Revision ID: 7d8417e8024e
Revises: 
Create Date: 2022-06-22 22:18:13.520780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d8417e8024e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('lastname', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('photo_profile', sa.String(length=150), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('roleTag', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=102), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP, nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP, nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP, nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
